### PR TITLE
Vinculin screen

### PR DESCRIPTION
**Pull request by simleo**
Adds `.screen` files and the scripts used to generate them for the "vinculin" datasets.

### CODE REVIEW

**Comment by joshmoore** [comment]
Looks sensible. Do you want me to activate travis before merging?

**Comment by simleo** [comment]
There's nothing for Travis to consume in the repo now. Maybe we can add that in a separate PR. I did run flake8 locally though :)

**Comment by simleo** [comment]
Uhm, hold on anyway. Looks like there's some more image data that's not captured by these `.screen` files

**Comment by simleo** [comment]
Never mind, just checked. There is also a `*_PCoverlay.tif` dataset, but:
1. It was not used in the analysis
2. It has _a lot_ of missing planes, so it wouldn't be particularly informative anyway

**Pull request merged**
